---
openapi: 3.0.0
info:
   version: 1.3.0
   title: testprodmongo open api specification
   description: testfeature API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8021
     description: testfeature
tags:
- name: person
paths:
   "/person/{id}":
      delete:
         tags:
         -  personController
         description: deletePerson
         parameters:
         -  in: "path"
            description: deletePerson
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  personController
         description: getPersonById
         parameters:
         -  in: "path"
            description: getPersonById
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/person/get/search":
      get:
         tags:
         -  personController
         description: searchPerson
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/person":
      put:
         tags:
         -  personController
         description: updatePerson
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/personController"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  personController
         description: getAllPerson
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  personController
         description: createPerson
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/personController"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/person/userid/created_by":
      get:
         tags:
         -  personController
         description: getNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      person:
         type: object
         properties:
            name:
               type: "string"
               description: Description
            age:
               type: "number"
               description: Description